/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import dynamic from "next/dynamic";
import ContactUs from "../components/ContactUs";
import Experiance from "../components/Experiance";
import Hero from "../components/Hero";
import Project from "../components/Project";
import Skills from "../components/Skills";
import Navbar from "../layouts/Navbar";
import Education from "../components/Education";
import SocialBar from "../components/design/SocialBar";

const Abouts = dynamic(() => import("../components/Abouts"), {
  ssr: false,
});

const Portfolio = dynamic(() => import("../components/Portfolio"), {
  ssr: false,
});
export default function Home() {

  return (
    <div className="bg-white dark:bg-[#0e1017] h-screen snap-y snap-mandatory overflow-scroll overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="text/javascript" src="/js/medium.js" />
      </Head>

      <main className="z-0">
        <SocialBar/>
        <Navbar />
        <section className="snap-center">
          <Hero />
        </section>
        <section className="snap-center">
          <Abouts />
        </section>
        <section className="snap-start">
          <Experiance />
        </section>
        <section className="snap-start">
          <Education />
        </section>
        <section className="snap-start lg:snap-center">
          <Portfolio />
        </section>
        <section className="snap-start">
          <Skills />
        </section>
        <section className="snap-center">
          <ContactUs />
        </section>
        <section className="snap-center">
          <Project />
        </section>
        {/* <Footer /> */}
      </main>
    </div>
  );

}
