import Head from "next/head";
import Image from "next/image";
import Abouts from "../components/Abouts";
import ContactUs from "../components/ContactUs";
import Experiance from "../components/Experiance";
import GoToTop from "../components/GoTop";
import Hero from "../components/Hero";
import Portfolio from "../components/Portfolio";
import Project from "../components/Project";
import Resume from "../components/Resume";
import Skills from "../components/Skills";
import Footer from "../layouts/Footer";
import Navbar from "../layouts/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-white dark:bg-black h-screen snap-y snap-mandatory overflow-scroll overflow-x-hidden">
      <Head>
        <title className="text-red-600">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="z-0">
        <Navbar />
        <section className="snap-center">
          <Hero />
        </section>
        <section className="snap-center">
          <Abouts />
        </section>
        <section className="snap-center">
          <Experiance />
        </section>
        <section className="snap-center">
          <Portfolio />
        </section>
        <section className="snap-start">
          <Skills />
        </section>
        <section className="snap-center">
          <ContactUs />
        </section>
        <section className="snap-center">
          <Project />
        </section>

        <Footer />
      </main>
    </div>
  );
}
